### ISSUE TITLE
installation issues while using documentation

### ISSUE THREAD

**Issue by aobszyns** [PaloAltoNetworks/SafeNetworking#40]
#1  pan:pan
setup.sh uses user and group "pan" and elasticsearch uses it for backup.
It is not mentioned in documentation at all.

#2  documentation is not clear on startup scenarios...
some pages mention tmux/screen some netion manual service preparations 
and setup.sh does something on it own.
Should be cleared what is the current design.

#3  CHANGEME mentioned near YML file edition is wrong.

#4  elasticsearch hostname is not there by default. DOC should have info about /etc/hosts or YML file editing.

**Comment by earcuri** [comment]
Thanks @aobszyns 
The newest documentation and code changes have been update to fix the above.  Specifically:

1. There is now a note in the Infrastructure Setup that tells the user that if they do not want to use the pan:pan user and group, that they need to change the settings in the first uncommented line in the file to reflect this.

2. The service startup has been deprecated, though the automated steps are still in the setup.sh file, just commented out.  It is recommended to use tmux and the Running SafeNetworking steps therein to run SFN.

3. The CHANGEME variable has been removed from all logstash conf files.  The newer files, as of v3.3 should have all necessary mappings done correctly. 

4. This has been fixed in the Infrastructure Setup directions.
